# Generated by Django 6.0.5 on 2026-06-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hapsari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('kategori', models.CharField(max_length=100)),
                ('nama_produk', models.CharField(max_length=255)),
                ('harga', models.IntegerField()),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
